defmodule AshPhoenixStarter.Repo.TenantMigrations.InitialMigrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_groups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:ledger_transfers, primary_key: false, prefix: prefix()) do
      add :id, :binary, null: false, primary_key: true
      add :amount, :money_with_currency, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :timestamp, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :from_account_id, :uuid
      add :to_account_id, :uuid
    end

    create table(:ledger_balances, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :balance, :money_with_currency

      add :transfer_id,
          references(:ledger_transfers,
            column: :id,
            name: "ledger_balances_transfer_id_fkey",
            type: :binary,
            prefix: prefix()
          ),
          null: false

      add :account_id, :uuid, null: false
    end

    create table(:ledger_accounts, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:ledger_transfers, prefix: prefix()) do
      modify :from_account_id,
             references(:ledger_accounts,
               column: :id,
               name: "ledger_transfers_from_account_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :to_account_id,
             references(:ledger_accounts,
               column: :id,
               name: "ledger_transfers_to_account_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:ledger_balances, prefix: prefix()) do
      modify :account_id,
             references(:ledger_accounts,
               column: :id,
               name: "ledger_balances_account_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(:ledger_balances, [:account_id, :transfer_id],
             name: "ledger_balances_unique_references_index"
           )

    alter table(:ledger_accounts, prefix: prefix()) do
      add :identifier, :text, null: false
      add :name, :text, null: false
      add :currency, :text, null: false
      add :nature, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ledger_accounts, [:identifier],
             name: "ledger_accounts_unique_identifier_index"
           )

    create table(:groups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:user_groups, prefix: prefix()) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "user_groups_group_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "user_groups_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:user_groups, [:group_id, :user_id],
             name: "user_groups_unique_name_index"
           )

    alter table(:groups, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:groups, [:name], name: "groups_unique_name_index")

    create table(:group_permissions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :action, :text, null: false
      add :resource, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_permissions_group_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create unique_index(:group_permissions, [:group_id, :resource, :action],
             name: "group_permissions_unique_group_permission_index"
           )

    create table(:farms, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :location, :text, null: false
      add :total_area, :float, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:farm_plantings, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :planting_date, :date, null: false
      add :expected_harvest_date, :date, null: false
      add :quantity_planted, :float, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :field_id, :uuid
      add :crop_id, :uuid, null: false
    end

    create table(:farm_planting_harvest, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :harvest_date, :date, null: false
      add :quantity_harvested, :float, null: false
      add :quality_grade, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :planting_id,
          references(:farm_plantings,
            column: :id,
            name: "farm_planting_harvest_planting_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:farm_labor_assignments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :assignment_date, :date, null: false
      add :hours_worked, :float, null: false
      add :task_description, :text
      add :cost, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :employee_id, :uuid, null: false
      add :planting_id, :uuid
      add :field_id, :uuid
    end

    create table(:farm_input_types, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :unit, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :planting_id,
          references(:farm_plantings,
            column: :id,
            name: "farm_input_types_planting_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:farm_input_applications, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:farm_labor_assignments, prefix: prefix()) do
      modify :employee_id,
             references(:farm_input_applications,
               column: :id,
               name: "farm_labor_assignments_employee_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :planting_id,
             references(:farm_plantings,
               column: :id,
               name: "farm_labor_assignments_planting_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:farm_input_applications, prefix: prefix()) do
      add :name, :text, null: false
      add :role, :text, null: false
      add :hire_date, :date, null: false
      add :hourly_rate, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_date, :date, null: false
      add :quantity_used, :float, null: false
      add :cost, :decimal

      add :planting_id,
          references(:farm_plantings,
            column: :id,
            name: "farm_input_applications_planting_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :input_type_id,
          references(:farm_input_types,
            column: :id,
            name: "farm_input_applications_input_type_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:farm_fields, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:farm_plantings, prefix: prefix()) do
      modify :field_id,
             references(:farm_fields,
               column: :id,
               name: "farm_plantings_field_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:farm_labor_assignments, prefix: prefix()) do
      modify :field_id,
             references(:farm_fields,
               column: :id,
               name: "farm_labor_assignments_field_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:farm_fields, prefix: prefix()) do
      add :name, :text, null: false
      add :area, :float, null: false
      add :soil_type, :text, null: false
      add :location_coordinates, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :farm_id,
          references(:farms,
            column: :id,
            name: "farm_fields_farm_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:farm_crops, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:farm_plantings, prefix: prefix()) do
      modify :crop_id,
             references(:farm_crops,
               column: :id,
               name: "farm_plantings_crop_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:farm_crops, prefix: prefix()) do
      add :name, :text, null: false
      add :type, :text, null: false
      add :planting_season, :text, null: false
      add :growth_duration, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:farm_crops, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :growth_duration
      remove :planting_season
      remove :type
      remove :name
    end

    drop constraint(:farm_plantings, "farm_plantings_crop_id_fkey")

    alter table(:farm_plantings, prefix: prefix()) do
      modify :crop_id, :uuid
    end

    drop table(:farm_crops, prefix: prefix())

    drop constraint(:farm_fields, "farm_fields_farm_id_fkey")

    alter table(:farm_fields, prefix: prefix()) do
      remove :farm_id
      remove :updated_at
      remove :inserted_at
      remove :location_coordinates
      remove :soil_type
      remove :area
      remove :name
    end

    drop constraint(:farm_labor_assignments, "farm_labor_assignments_field_id_fkey")

    alter table(:farm_labor_assignments, prefix: prefix()) do
      modify :field_id, :uuid
    end

    drop constraint(:farm_plantings, "farm_plantings_field_id_fkey")

    alter table(:farm_plantings, prefix: prefix()) do
      modify :field_id, :uuid
    end

    drop table(:farm_fields, prefix: prefix())

    drop constraint(:farm_input_applications, "farm_input_applications_planting_id_fkey")

    drop constraint(:farm_input_applications, "farm_input_applications_input_type_id_fkey")

    alter table(:farm_input_applications, prefix: prefix()) do
      remove :input_type_id
      remove :planting_id
      remove :cost
      remove :quantity_used
      remove :application_date
      remove :updated_at
      remove :inserted_at
      remove :hourly_rate
      remove :hire_date
      remove :role
      remove :name
    end

    drop constraint(:farm_labor_assignments, "farm_labor_assignments_employee_id_fkey")

    drop constraint(:farm_labor_assignments, "farm_labor_assignments_planting_id_fkey")

    alter table(:farm_labor_assignments, prefix: prefix()) do
      modify :planting_id, :uuid
      modify :employee_id, :uuid
    end

    drop table(:farm_input_applications, prefix: prefix())

    drop constraint(:farm_input_types, "farm_input_types_planting_id_fkey")

    drop table(:farm_input_types, prefix: prefix())

    drop table(:farm_labor_assignments, prefix: prefix())

    drop constraint(:farm_planting_harvest, "farm_planting_harvest_planting_id_fkey")

    drop table(:farm_planting_harvest, prefix: prefix())

    drop table(:farm_plantings, prefix: prefix())

    drop table(:farms, prefix: prefix())

    drop_if_exists unique_index(:group_permissions, [:group_id, :resource, :action],
                     name: "group_permissions_unique_group_permission_index"
                   )

    drop constraint(:group_permissions, "group_permissions_group_id_fkey")

    drop table(:group_permissions, prefix: prefix())

    drop_if_exists unique_index(:groups, [:name], name: "groups_unique_name_index")

    alter table(:groups, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:user_groups, [:group_id, :user_id],
                     name: "user_groups_unique_name_index"
                   )

    drop constraint(:user_groups, "user_groups_group_id_fkey")

    drop constraint(:user_groups, "user_groups_user_id_fkey")

    alter table(:user_groups, prefix: prefix()) do
      modify :user_id, :uuid
      modify :group_id, :uuid
    end

    drop table(:groups, prefix: prefix())

    drop_if_exists unique_index(:ledger_accounts, [:identifier],
                     name: "ledger_accounts_unique_identifier_index"
                   )

    alter table(:ledger_accounts, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :nature
      remove :currency
      remove :name
      remove :identifier
    end

    drop_if_exists unique_index(:ledger_balances, [:account_id, :transfer_id],
                     name: "ledger_balances_unique_references_index"
                   )

    drop constraint(:ledger_balances, "ledger_balances_account_id_fkey")

    alter table(:ledger_balances, prefix: prefix()) do
      modify :account_id, :uuid
    end

    drop constraint(:ledger_transfers, "ledger_transfers_from_account_id_fkey")

    drop constraint(:ledger_transfers, "ledger_transfers_to_account_id_fkey")

    alter table(:ledger_transfers, prefix: prefix()) do
      modify :to_account_id, :uuid
      modify :from_account_id, :uuid
    end

    drop table(:ledger_accounts, prefix: prefix())

    drop constraint(:ledger_balances, "ledger_balances_transfer_id_fkey")

    drop table(:ledger_balances, prefix: prefix())

    drop table(:ledger_transfers, prefix: prefix())

    drop table(:user_groups, prefix: prefix())
  end
end
