defmodule AshPhoenixStarter.Repo.TenantMigrations.AddUserImpersonationTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:farm_plantings, prefix: prefix()) do
      modify :crop_id, :uuid, null: true
    end

    drop constraint(:farm_labor_assignments, "farm_labor_assignments_employee_id_fkey")

    alter table(:farm_input_applications, prefix: prefix()) do
      remove :hourly_rate
      remove :hire_date
      remove :role
      remove :name
    end

    create table(:farm_employees, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:farm_labor_assignments, prefix: prefix()) do
      modify :employee_id,
             references(:farm_employees,
               column: :id,
               name: "farm_labor_assignments_employee_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:farm_employees, prefix: prefix()) do
      add :name, :text, null: false
      add :role, :text, null: false
      add :hire_date, :date, null: false
      add :hourly_rate, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:farm_employees, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :hourly_rate
      remove :hire_date
      remove :role
      remove :name
    end

    drop constraint(:farm_labor_assignments, "farm_labor_assignments_employee_id_fkey")

    alter table(:farm_labor_assignments, prefix: prefix()) do
      modify :employee_id,
             references(:farm_input_applications,
               column: :id,
               name: "farm_labor_assignments_employee_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    drop table(:farm_employees, prefix: prefix())

    alter table(:farm_input_applications, prefix: prefix()) do
      add :name, :text, null: false
      add :role, :text, null: false
      add :hire_date, :date, null: false
      add :hourly_rate, :decimal, null: false
    end

    alter table(:farm_plantings, prefix: prefix()) do
      modify :crop_id, :uuid, null: false
    end
  end
end
