defmodule AshPhoenixStarter.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_impersonations) do
      remove :team_id
      remove :end_timestamp
      remove :start_timestamp
      add :started_at, :utc_datetime, null: false
      add :ended_at, :utc_datetime

      add :team_domain,
          references(:teams,
            column: :id,
            name: "user_impersonations_team_domain_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:user_impersonations, "user_impersonations_team_domain_fkey")

    alter table(:user_impersonations) do
      remove :team_domain
      remove :ended_at
      remove :started_at
      add :start_timestamp, :utc_datetime, null: false
      add :end_timestamp, :utc_datetime

      add :team_id,
          references(:teams,
            column: :id,
            name: "user_impersonations_team_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
