defmodule AshPhoenixStarter.Repo.Migrations.AddUserImpersonationTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_impersonations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :start_timestamp, :utc_datetime, null: false
      add :end_timestamp, :utc_datetime
      add :reason, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :impersonator_user_id,
          references(:users,
            column: :id,
            name: "user_impersonations_impersonator_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :impersonated_user_id,
          references(:users,
            column: :id,
            name: "user_impersonations_impersonated_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :team_id,
          references(:teams,
            column: :id,
            name: "user_impersonations_team_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:user_impersonations, "user_impersonations_impersonator_user_id_fkey")

    drop constraint(:user_impersonations, "user_impersonations_impersonated_user_id_fkey")

    drop constraint(:user_impersonations, "user_impersonations_team_id_fkey")

    drop table(:user_impersonations)
  end
end
