defmodule AshPhoenixStarter.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_impersonations) do
      modify :started_at, :utc_datetime_usec,
        null: true,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:user_impersonations) do
      modify :started_at, :utc_datetime, null: false, default: nil
    end
  end
end
