defmodule AshPhoenixStarter.Repo.Migrations.InitialMigrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text
      add :confirmed_at, :utc_datetime_usec
      add :current_team, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:user_teams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_teams_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :team_id, :uuid
    end

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:teams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:user_teams) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "user_teams_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:user_teams, [:user_id, :team_id],
             name: "user_teams_unique_user_team_index"
           )

    alter table(:teams) do
      add :name, :text, null: false
      add :domain, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "teams_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:teams, [:domain], name: "teams_unique_domain_index")

    alter table(:users) do
      modify :current_team,
             references(:teams,
               column: :domain,
               name: "users_current_team_fkey",
               type: :text,
               prefix: "public"
             )
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop constraint(:users, "users_current_team_fkey")

    alter table(:users) do
      modify :current_team, :text
    end

    drop_if_exists unique_index(:teams, [:domain], name: "teams_unique_domain_index")

    drop constraint(:teams, "teams_owner_user_id_fkey")

    alter table(:teams) do
      remove :owner_user_id
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :domain
      remove :name
    end

    drop_if_exists unique_index(:user_teams, [:user_id, :team_id],
                     name: "user_teams_unique_user_team_index"
                   )

    drop constraint(:user_teams, "user_teams_team_id_fkey")

    alter table(:user_teams) do
      modify :team_id, :uuid
    end

    drop table(:teams)

    drop table(:tokens)

    drop constraint(:user_teams, "user_teams_user_id_fkey")

    drop table(:user_teams)

    drop table(:users)
  end
end
