defmodule Samba.Repo.Migrations.MakePhpbbUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :phpbb_user_id,
          references(:phpbb_users,
            column: :user_id,
            name: "users_phpbb_user_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_phpbb_user_id_fkey")

    alter table(:users) do
      remove :phpbb_user_id
    end
  end
end
