defmodule Samba.Repo.Migrations.PhpbbNils do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:phpbb_posts_text) do
      modify :bbcode_uid, :text, null: true
    end
  end

  def down do
    alter table(:phpbb_posts_text) do
      modify :bbcode_uid, :text, null: false
    end
  end
end
