defmodule Samba.Repo.Migrations.SettingsWConcache do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:app_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :value, :text, null: false
      add :type, :text, null: false, default: "string"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:app_settings, [:key], name: "app_settings_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:app_settings, [:key], name: "app_settings_unique_key_index")

    drop table(:app_settings)
  end
end
