defmodule Samba.Repo.Migrations.PhpbbAttachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:phpbb_attachments_desc, primary_key: false) do
      add :attach_id, :bigserial, null: false, primary_key: true
      add :physical_filename, :text, null: false
      add :real_filename, :text, null: false
      add :download_count, :bigint, null: false, default: 0
      add :comment, :text
      add :extension, :text
      add :mimetype, :text
      add :filesize, :bigint, null: false
      add :filetime, :bigint, null: false
      add :thumbnail, :bigint, null: false, default: 0
    end

    create table(:phpbb_attachments, primary_key: false) do
      add :attach_id, :bigint, null: false, primary_key: true
      add :post_id, :bigint, null: false
      add :privmsgs_id, :bigint, null: false, default: 0
      add :user_id_1, :bigint, null: false
      add :user_id_2, :bigint, null: false, default: 0
    end
  end

  def down do
    drop table(:phpbb_attachments)

    drop table(:phpbb_attachments_desc)
  end
end
