defmodule Samba.Repo.Migrations.AddPhpPostsRelationsPostTexts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:phpbb_posts_text) do
      modify :post_id,
             references(:phpbb_posts,
               column: :post_id,
               name: "phpbb_posts_text_post_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create index(:phpbb_posts_text, [:post_id])
  end

  def down do
    drop_if_exists index(:phpbb_posts_text, [:post_id])

    drop constraint(:phpbb_posts_text, "phpbb_posts_text_post_id_fkey")

    alter table(:phpbb_posts_text) do
      modify :post_id, :bigint
    end
  end
end
