defmodule Samba.Repo.Migrations.ModifyPhpbb do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:phpbb_forums) do
      modify :auth_attachments, :bigint, null: true
      modify :auth_vote, :bigint, null: true
      modify :auth_pollcreate, :bigint, null: true
      modify :auth_sticky, :bigint, null: true
      modify :auth_announce, :bigint, null: true
      modify :auth_delete, :bigint, null: true
      modify :auth_edit, :bigint, null: true
      modify :auth_reply, :bigint, null: true
      modify :auth_post, :bigint, null: true
      modify :auth_read, :bigint, null: true
      modify :auth_view, :bigint, null: true
      modify :prune_enable, :bigint, null: true
      modify :forum_order, :bigint, null: true
      modify :forum_status, :bigint, null: true
      modify :forum_desc, :text, null: false
    end
  end

  def down do
    alter table(:phpbb_forums) do
      modify :forum_desc, :text, null: true
      modify :forum_status, :bigint, null: false
      modify :forum_order, :bigint, null: false
      modify :prune_enable, :bigint, null: false
      modify :auth_view, :bigint, null: false
      modify :auth_read, :bigint, null: false
      modify :auth_post, :bigint, null: false
      modify :auth_reply, :bigint, null: false
      modify :auth_edit, :bigint, null: false
      modify :auth_delete, :bigint, null: false
      modify :auth_announce, :bigint, null: false
      modify :auth_sticky, :bigint, null: false
      modify :auth_pollcreate, :bigint, null: false
      modify :auth_vote, :bigint, null: false
      modify :auth_attachments, :bigint, null: false
    end
  end
end
