defmodule Samba.Repo.Migrations.DailyStatsUpdate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:daily_stats, [:date])

    drop_if_exists unique_index(:daily_stats, [:date], name: "daily_stats_unique_date_index")

    rename table(:daily_stats), :date, to: :recorded_at

    create index(:daily_stats, [:recorded_at], unique: true)

    alter table(:daily_stats) do
      modify :recorded_at, :utc_datetime
    end

    create unique_index(:daily_stats, [:recorded_at],
             name: "daily_stats_unique_recorded_at_index"
           )
  end

  def down do
    drop_if_exists unique_index(:daily_stats, [:recorded_at],
                     name: "daily_stats_unique_recorded_at_index"
                   )

    alter table(:daily_stats) do
      modify :recorded_at, :date
    end

    drop_if_exists index(:daily_stats, [:recorded_at])

    rename table(:daily_stats), :recorded_at, to: :date

    create unique_index(:daily_stats, [:date], name: "daily_stats_unique_date_index")

    create index(:daily_stats, [:date], unique: true)
  end
end
