defmodule Samba.Repo.Migrations.DailyStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:daily_stats, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date, :date, null: false
      add :total_online, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:daily_stats, [:date], unique: true)

    create unique_index(:daily_stats, [:date], name: "daily_stats_unique_date_index")
  end

  def down do
    drop_if_exists unique_index(:daily_stats, [:date], name: "daily_stats_unique_date_index")

    drop_if_exists index(:daily_stats, [:date])

    drop table(:daily_stats)
  end
end
