defmodule Samba.Repo.Migrations.Phpbb do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:phpbb_posts, primary_key: false) do
      add :post_id, :bigserial, null: false, primary_key: true
      add :topic_id, :bigint, null: false, default: 0
      add :forum_id, :bigint, null: false, default: 0
      add :poster_id, :bigint, null: false, default: 0
      add :post_username, :bigint, null: false, default: 0
      add :post_time, :bigint, null: false, default: 0
      add :poster_ip, :bigint, null: false, default: 0
      add :enable_bbcode, :bigint, null: false, default: 1
      add :enable_html, :bigint, null: false, default: 0
      add :enable_smilies, :bigint, null: false, default: 1
      add :enable_sig, :bigint, null: false, default: 1
      add :post_edit_time, :bigint
      add :post_edit_count, :bigint, null: false, default: 0
    end

    create table(:phpbb_themes_name, primary_key: false) do
      add :themes_id, :bigint, null: false
      add :tr_color1, :text
      add :tr_color2, :text
      add :tr_color3, :text
      add :tr_class1, :text
      add :tr_class2, :text
      add :tr_class3, :text
      add :td_color1, :text
      add :td_color2, :text
      add :td_color3, :text
      add :fontface1, :text
      add :fontface2, :text
      add :fontface3, :text
      add :fontsize1, :text
      add :fontsize2, :text
      add :fontsize3, :text
      add :fontcolor1, :text
      add :fontcolor2, :text
      add :fontcolor3, :text
      add :span_class1, :text
      add :span_class2, :text
      add :span_class3, :text
    end

    create table(:phpbb_user_group, primary_key: false) do
      add :group_id, :bigint, null: false, default: 0, primary_key: true
      add :user_id, :bigint, null: false, default: 0
      add :user_pending, :bigint, null: false
    end

    create unique_index(:phpbb_user_group, [:group_id],
             name: "phpbb_user_group_group_id_phpbb_user_group_index_index"
           )

    create unique_index(:phpbb_user_group, [:user_id],
             name: "phpbb_user_group_user_id_phpbb_user_group_index_index"
           )

    create table(:phpbb_sessions_keys, primary_key: false) do
      add :phpbb_sessions_keys, :bigserial, null: false, primary_key: true
      add :user_id, :bigint, null: false
      add :last_ip, :text
      add :last_login, :text
    end

    create table(:phpbb_categories, primary_key: false) do
      add :cat_id, :bigserial, null: false, primary_key: true
      add :cat_title, :text
      add :cat_order, :bigint
    end

    create table(:phpbb_themes, primary_key: false) do
      add :themes_id, :bigserial, null: false, primary_key: true
    end

    alter table(:phpbb_themes_name) do
      modify :themes_id,
             references(:phpbb_themes,
               column: :themes_id,
               name: "phpbb_themes_name_themes_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_themes) do
      add :style_name, :text
      add :template_name, :text
      add :head_stylesheet, :text
      add :body_bgcolor, :text
      add :body_text, :text
      add :body_link, :text
      add :body_vlink, :text
      add :body_alink, :text
      add :body_hlink, :text
      add :tr_color1, :text
      add :tr_color2, :text
      add :tr_color3, :text
      add :tr_class1, :text
      add :tr_class2, :text
      add :tr_class3, :text
      add :td_color1, :text
      add :td_color2, :text
      add :td_color3, :text
      add :fontface1, :text
      add :fontface2, :text
      add :fontface3, :text
      add :fontsize1, :text
      add :fontsize2, :text
      add :fontsize3, :text
      add :fontcolor1, :text
      add :fontcolor2, :text
      add :fontcolor3, :text
      add :span_class1, :text
      add :span_class2, :text
      add :span_class3, :text
      add :img_size_poll, :text
      add :img_size_privmsg, :text
    end

    create table(:phpbb_forums, primary_key: false) do
      add :forum_id, :bigserial, null: false, primary_key: true

      add :forum_last_post_id,
          references(:phpbb_posts,
            column: :post_id,
            name: "phpbb_forums_forum_last_post_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :cat_id,
          references(:phpbb_categories,
            column: :cat_id,
            name: "phpbb_forums_cat_id_fkey",
            type: :bigint,
            prefix: "public"
          ), null: false

      add :forum_name, :text, null: false
      add :forum_desc, :text
      add :forum_status, :bigint, null: false, default: 0
      add :forum_order, :bigint, null: false, default: 1
      add :prune_enable, :bigint, null: false, default: 0
      add :prune_next, :bigint
      add :auth_view, :bigint, null: false, default: 0
      add :auth_read, :bigint, null: false, default: 0
      add :auth_post, :bigint, null: false, default: 0
      add :auth_reply, :bigint, null: false, default: 0
      add :auth_edit, :bigint, null: false, default: 0
      add :auth_delete, :bigint, null: false, default: 0
      add :auth_announce, :bigint, null: false, default: 0
      add :auth_sticky, :bigint, null: false, default: 0
      add :auth_pollcreate, :bigint, null: false, default: 0
      add :auth_vote, :bigint, null: false, default: 0
      add :auth_attachments, :bigint, null: false, default: 0
    end

    create unique_index(:phpbb_forums, [:forum_id],
             name: "phpbb_forums_forum_id_phpbb_forums_index_index"
           )

    create table(:phpbb_privmsgs, primary_key: false) do
      add :privmsgs_id, :bigserial, null: false, primary_key: true
      add :privmsgs_from_userid, :bigint, null: false
      add :privmsgs_to_userid, :bigint, null: false
      add :privmsgs_type, :bigint, null: false, default: 0
      add :privmsgs_subject, :text, null: false, default: "0"
      add :privmsgs_date, :bigint, null: false, default: 0
      add :privmsgs_ip, :text, null: false
      add :privmsgs_enable_bbcode, :bigint, null: false, default: 1
      add :privmsgs_enable_html, :bigint, null: false, default: 0
      add :privmsgs_enable_smilies, :bigint, null: false, default: 1
      add :privmsgs_attach_sig, :bigint, null: false, default: 1
    end

    create unique_index(:phpbb_privmsgs, [:privmsgs_from_userid],
             name: "phpbb_privmsgs_privmsgs_from_userid_phpbb_privmsgs_index_index"
           )

    create unique_index(:phpbb_privmsgs, [:privmsgs_to_userid],
             name: "phpbb_privmsgs_privmsgs_to_userid_phpbb_privmsgs_index_index"
           )

    create table(:phpbb_privmsgs_text, primary_key: false) do
      add :privmsgs_text_id,
          references(:phpbb_privmsgs,
            column: :privmsgs_id,
            name: "phpbb_privmsgs_text_privmsgs_text_id_fkey",
            type: :bigint,
            prefix: "public"
          ), default: 0, null: false

      add :privmsgs_bbcode_uid, :bigint, null: false, default: 0
      add :privmsgs_text, :text, null: false
    end

    create table(:phpbb_vote_voters, primary_key: false) do
      add :vote_id, :bigint, null: false, default: 0, primary_key: true
      add :vote_user_id, :bigint, null: false, default: 0
      add :vote_user_ip, :text, null: false
    end

    create unique_index(:phpbb_vote_voters, [:vote_id],
             name: "phpbb_vote_voters_vote_id_phpbb_vote_voters_index_index"
           )

    create unique_index(:phpbb_vote_voters, [:vote_user_id],
             name: "phpbb_vote_voters_vote_user_id_phpbb_vote_voters_index_index"
           )

    create unique_index(:phpbb_vote_voters, [:vote_user_ip],
             name: "phpbb_vote_voters_vote_user_ip_phpbb_vote_voters_index_index"
           )

    create table(:phpbb_search_results, primary_key: false) do
      add :search_id, :bigint, null: false, default: 0, primary_key: true
      add :session_id, :bigint, null: false, default: 0
      add :search_time, :bigint, null: false, default: 0
      add :search_array, :bigint, null: false
    end

    create unique_index(:phpbb_search_results, [:session_id],
             name: "phpbb_search_results_session_id_phpbb_search_results_index_index"
           )

    create table(:phpbb_disallow, primary_key: false) do
      add :disallow_id, :bigserial, null: false, primary_key: true
      add :disallow_username, :bigint
    end

    create table(:phpbb_auth_access, primary_key: false) do
      add :group_id, :bigint, null: false, default: 0, primary_key: true
      add :forum_id, :bigint, null: false, default: 0, primary_key: true
      add :auth_view, :bigint, null: false, default: 0
      add :auth_read, :bigint, null: false, default: 0
      add :auth_post, :bigint, null: false, default: 0
      add :auth_reply, :bigint, null: false, default: 0
      add :auth_edit, :bigint, null: false, default: 0
      add :auth_delete, :bigint, null: false, default: 0
      add :auth_sticky, :bigint, null: false, default: 0
      add :auth_announce, :bigint, null: false, default: 0
      add :auth_vote, :bigint, null: false, default: 0
      add :auth_pollcreate, :bigint, null: false, default: 0
      add :auth_attachments, :bigint, null: false, default: 0
      add :auth_mod, :bigint, null: false, default: 0
    end

    create table(:phpbb_words, primary_key: false) do
      add :word_id, :bigserial, null: false, primary_key: true
      add :word, :text, null: false, default: ""
      add :replacement, :text, null: false, default: ""
    end

    create table(:phpbb_banlist, primary_key: false) do
      add :ban_id, :bigserial, null: false, primary_key: true
      add :ban_userid, :bigint, null: false
      add :ban_ip, :text
      add :ban_email, :text
    end

    create table(:phpbb_smilies, primary_key: false) do
      add :smilies_id, :bigserial, null: false, primary_key: true
      add :code, :text
      add :smile_url, :text
      add :emoticon, :text
    end

    create table(:phpbb_config, primary_key: false) do
      add :config_name, :text, null: false, primary_key: true
      add :config_value, :bigint, null: false
    end

    create table(:phpbb_posts_text, primary_key: false) do
      add :post_id,
          references(:phpbb_posts,
            column: :post_id,
            name: "phpbb_posts_text_post_id_fkey",
            type: :bigint,
            prefix: "public"
          ), default: 0, primary_key: true, null: false

      add :bbcode_uid, :text, null: false, default: ""
      add :post_subject, :text, null: false
      add :post_text, :text, null: false
    end

    create table(:phpbb_forum_prune, primary_key: false) do
      add :prune_id, :bigserial, null: false, primary_key: true

      add :forum_id,
          references(:phpbb_forums,
            column: :forum_id,
            name: "phpbb_forum_prune_forum_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :prune_days, :bigint, null: false
      add :prune_freq, :bigint, null: false
    end

    create table(:phpbb_pages, primary_key: false) do
      add :page_id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :body, :text
    end

    create table(:phpbb_search_wordmatch, primary_key: false) do
      add :word_id, :bigint, null: false, default: 0
      add :post_id, :bigint, null: false, default: 0
      add :title_match, :text, null: false, default: "0"
    end

    create unique_index(:phpbb_search_wordmatch, [:post_id],
             name: "phpbb_search_wordmatch_post_id_phpbb_search_wordmatch_index_index"
           )

    create unique_index(:phpbb_search_wordmatch, [:word_id],
             name: "phpbb_search_wordmatch_word_id_phpbb_search_wordmatch_index_index"
           )

    create table(:phpbb_topics, primary_key: false) do
      add :topic_id, :bigserial, null: false, primary_key: true
    end

    alter table(:phpbb_posts) do
      modify :topic_id,
             references(:phpbb_topics,
               column: :topic_id,
               name: "phpbb_posts_topic_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :forum_id,
             references(:phpbb_forums,
               column: :forum_id,
               name: "phpbb_posts_forum_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_topics) do
      add :forum_id,
          references(:phpbb_forums,
            column: :forum_id,
            name: "phpbb_topics_forum_id_fkey",
            type: :bigint,
            prefix: "public"
          ), null: false

      add :topic_poster, :bigint, null: false
      add :first_post_id, :bigint
      add :last_post_id, :bigint
      add :topic_moved_id, :bigint
      add :topic_title, :text, null: false, default: ""
      add :topic_time, :bigint, null: false, default: 0
      add :topic_views, :bigint, null: false, default: 0
      add :topic_replies, :bigint, null: false, default: 0
      add :topic_status, :bigint, null: false, default: 0
      add :topic_vote, :bigint, null: false, default: 0
      add :topic_type, :bigint, null: false, default: 0
    end

    create table(:phpbb_ranks, primary_key: false) do
      add :rank_id, :bigserial, null: false, primary_key: true
      add :rank_title, :text, null: false, default: ""
      add :rank_min, :bigint, null: false, default: 0
      add :rank_special, :bigint, null: false, default: 0
      add :rank_image, :text
    end

    create table(:phpbb_faq_items, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :variable, :text, null: false
      add :section, :text, null: false
      add :question, :text, null: false
      add :answer, :text
      add :position, :bigint, null: false
    end

    create table(:phpbb_topic_watch, primary_key: false) do
      add :topic_id,
          references(:phpbb_topics,
            column: :topic_id,
            name: "phpbb_topic_watch_topic_id_fkey",
            type: :bigint,
            prefix: "public"
          ), null: false

      add :user_id, :bigint, null: false
      add :notify_status, :text, null: false
    end

    create unique_index(:phpbb_topic_watch, [:topic_id],
             name: "phpbb_topic_watch_topic_id_phpbb_topics_watch_index_index"
           )

    create unique_index(:phpbb_topic_watch, [:user_id],
             name: "phpbb_topic_watch_user_id_phpbb_topics_watch_index_index"
           )

    create table(:phpbb_sessions, primary_key: false) do
      add :session_id, :bigserial, null: false, primary_key: true
    end

    alter table(:phpbb_search_results) do
      modify :session_id,
             references(:phpbb_sessions,
               column: :session_id,
               name: "phpbb_search_results_session_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_sessions) do
      add :session_user_id, :bigint, null: false
      add :session_start, :text
      add :session_time, :text
      add :session_ip, :text
      add :session_page, :text
      add :session_logged_in, :text
      add :session_admin, :text
    end

    create table(:phpbb_vote_desc, primary_key: false) do
      add :vote_id, :bigserial, null: false, primary_key: true
    end

    alter table(:phpbb_vote_voters) do
      modify :vote_id,
             references(:phpbb_vote_desc,
               column: :vote_id,
               name: "phpbb_vote_voters_vote_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_vote_desc) do
      add :topic_id,
          references(:phpbb_topics,
            column: :topic_id,
            name: "phpbb_vote_desc_topic_id_fkey",
            type: :bigint,
            prefix: "public"
          ), default: 0, null: false

      add :vote_text, :text, null: false
      add :vote_start, :bigint, null: false, default: 0
      add :vote_length, :bigint, null: false, default: 0
    end

    create unique_index(:phpbb_vote_desc, [:topic_id],
             name: "phpbb_vote_desc_topic_id_phpbb_vote_desc_index_index"
           )

    create table(:phpbb_confirm, primary_key: false) do
      add :confirm_id, :text, null: false, default: "", primary_key: true

      add :session_id,
          references(:phpbb_sessions,
            column: :session_id,
            name: "phpbb_confirm_session_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :code, :text
    end

    create table(:phpbb_groups, primary_key: false) do
      add :group_id, :bigserial, null: false, primary_key: true
    end

    alter table(:phpbb_auth_access) do
      modify :group_id,
             references(:phpbb_groups,
               column: :group_id,
               name: "phpbb_auth_access_group_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :forum_id,
             references(:phpbb_forums,
               column: :forum_id,
               name: "phpbb_auth_access_forum_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_groups) do
      add :group_name, :text, null: false
      add :group_moderator, :bigint, null: false, default: 0
      add :group_single_user, :bigint, null: false, default: 0
      add :group_type, :bigint, null: false, default: 1
      add :group_description, :text
    end

    alter table(:users) do
      add :phpbb_user_id, :bigint
      add :username, :text
    end

    create table(:phpbb_users, primary_key: false) do
      add :user_id, :bigserial, null: false, primary_key: true
    end

    alter table(:phpbb_posts) do
      modify :poster_id,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_posts_poster_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_user_group) do
      modify :user_id,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_user_group_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_sessions_keys) do
      modify :user_id,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_sessions_keys_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_privmsgs) do
      modify :privmsgs_from_userid,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_privmsgs_privmsgs_from_userid_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :privmsgs_to_userid,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_privmsgs_privmsgs_to_userid_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_vote_voters) do
      modify :vote_user_id,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_vote_voters_vote_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_banlist) do
      modify :ban_userid,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_banlist_ban_userid_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_topics) do
      modify :topic_poster,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_topics_topic_poster_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :first_post_id,
             references(:phpbb_posts,
               column: :post_id,
               name: "phpbb_topics_first_post_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :last_post_id,
             references(:phpbb_posts,
               column: :post_id,
               name: "phpbb_topics_last_post_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_topic_watch) do
      modify :user_id,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_topic_watch_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_sessions) do
      modify :session_user_id,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_sessions_session_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_groups) do
      modify :group_moderator,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_groups_group_moderator_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:users) do
      modify :phpbb_user_id,
             references(:phpbb_users,
               column: :user_id,
               name: "users_phpbb_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_users) do
      add :user_rank,
          references(:phpbb_ranks,
            column: :rank_id,
            name: "phpbb_users_user_rank_fkey",
            type: :bigint,
            prefix: "public"
          ), null: false

      add :user_active, :bigint
      add :username, :text, null: false
      add :user_regdate, :bigint, null: false, default: 0
      add :user_password, :text, null: false, default: "0"
      add :user_session_time, :bigint, null: false, default: 0
      add :user_session_page, :bigint, null: false, default: 0
      add :user_lastvisit, :bigint, null: false, default: 0
      add :user_email, :text
      add :user_icq, :text
      add :user_website, :text
      add :user_occ, :text
      add :user_from, :text
      add :user_interests, :text
      add :user_sig, :text
      add :user_sig_bbcode_uid, :text
      add :user_style, :bigint
      add :user_aim, :text
      add :user_yim, :text
      add :user_msnm, :text
      add :user_posts, :bigint, null: false, default: 0
      add :user_new_privmsg, :bigint, null: false, default: 0
      add :user_unread_privmsg, :bigint, null: false, default: 0
      add :user_last_privmsg, :bigint, null: false, default: 0
      add :user_login_tries, :bigint, null: false, default: 0
      add :user_last_login_try, :bigint, null: false, default: 0
      add :user_emailtime, :bigint
      add :user_viewemail, :bigint
      add :user_attachsig, :bigint
      add :user_allowhtml, :bigint, default: 1
      add :user_allowbbcode, :bigint, default: 1
      add :user_allowsmile, :bigint, default: 1
      add :user_allow_pm, :bigint, null: false, default: 0
      add :user_allowavatar, :bigint, null: false, default: 1
      add :user_allow_viewonline, :bigint, null: false, default: 1
      add :user_avatar, :text
      add :user_avatar_type, :bigint, null: false, default: 0
      add :user_level, :bigint, default: 0
      add :user_lang, :text
      add :user_timezone, :decimal, null: false, default: "0.0"
      add :user_dateformat, :text, null: false, default: "d M Y H:i"
      add :user_notify_pm, :bigint, null: false, default: 0
      add :user_popup_pm, :bigint, null: false, default: 0
      add :user_notify, :bigint
      add :user_actkey, :text
      add :user_newpasswd, :text
    end

    create table(:phpbb_vote_results, primary_key: false) do
      add :vote_id,
          references(:phpbb_vote_desc,
            column: :vote_id,
            name: "phpbb_vote_results_vote_id_fkey",
            type: :bigint,
            prefix: "public"
          ), default: 0, null: false

      add :vote_option_id, :bigint, null: false, default: 0, primary_key: true
      add :vote_option_text, :text, null: false
      add :vote_result, :bigint, null: false, default: 0
    end

    create table(:phpbb_search_wordlist, primary_key: false) do
      add :word_id, :bigserial, null: false, primary_key: true
    end

    alter table(:phpbb_search_wordmatch) do
      modify :word_id,
             references(:phpbb_search_wordlist,
               column: :word_id,
               name: "phpbb_search_wordmatch_word_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :post_id,
             references(:phpbb_posts,
               column: :post_id,
               name: "phpbb_search_wordmatch_post_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:phpbb_search_wordlist) do
      add :word_text, :text, null: false, default: ""
      add :word_common, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:phpbb_search_wordlist) do
      remove :word_common
      remove :word_text
    end

    drop constraint(:phpbb_search_wordmatch, "phpbb_search_wordmatch_word_id_fkey")

    drop constraint(:phpbb_search_wordmatch, "phpbb_search_wordmatch_post_id_fkey")

    alter table(:phpbb_search_wordmatch) do
      modify :post_id, :bigint
      modify :word_id, :bigint
    end

    drop table(:phpbb_search_wordlist)

    drop constraint(:phpbb_vote_results, "phpbb_vote_results_vote_id_fkey")

    drop table(:phpbb_vote_results)

    drop constraint(:phpbb_users, "phpbb_users_user_rank_fkey")

    alter table(:phpbb_users) do
      remove :user_newpasswd
      remove :user_actkey
      remove :user_notify
      remove :user_popup_pm
      remove :user_notify_pm
      remove :user_dateformat
      remove :user_timezone
      remove :user_lang
      remove :user_level
      remove :user_avatar_type
      remove :user_avatar
      remove :user_allow_viewonline
      remove :user_allowavatar
      remove :user_allow_pm
      remove :user_allowsmile
      remove :user_allowbbcode
      remove :user_allowhtml
      remove :user_attachsig
      remove :user_viewemail
      remove :user_emailtime
      remove :user_last_login_try
      remove :user_login_tries
      remove :user_last_privmsg
      remove :user_unread_privmsg
      remove :user_new_privmsg
      remove :user_posts
      remove :user_msnm
      remove :user_yim
      remove :user_aim
      remove :user_style
      remove :user_sig_bbcode_uid
      remove :user_sig
      remove :user_interests
      remove :user_from
      remove :user_occ
      remove :user_website
      remove :user_icq
      remove :user_email
      remove :user_lastvisit
      remove :user_session_page
      remove :user_session_time
      remove :user_password
      remove :user_regdate
      remove :username
      remove :user_active
      remove :user_rank
    end

    drop constraint(:users, "users_phpbb_user_id_fkey")

    alter table(:users) do
      modify :phpbb_user_id, :bigint
    end

    drop constraint(:phpbb_groups, "phpbb_groups_group_moderator_fkey")

    alter table(:phpbb_groups) do
      modify :group_moderator, :bigint
    end

    drop constraint(:phpbb_sessions, "phpbb_sessions_session_user_id_fkey")

    alter table(:phpbb_sessions) do
      modify :session_user_id, :bigint
    end

    drop constraint(:phpbb_topic_watch, "phpbb_topic_watch_user_id_fkey")

    alter table(:phpbb_topic_watch) do
      modify :user_id, :bigint
    end

    drop constraint(:phpbb_topics, "phpbb_topics_topic_poster_fkey")

    drop constraint(:phpbb_topics, "phpbb_topics_first_post_id_fkey")

    drop constraint(:phpbb_topics, "phpbb_topics_last_post_id_fkey")

    alter table(:phpbb_topics) do
      modify :last_post_id, :bigint
      modify :first_post_id, :bigint
      modify :topic_poster, :bigint
    end

    drop constraint(:phpbb_banlist, "phpbb_banlist_ban_userid_fkey")

    alter table(:phpbb_banlist) do
      modify :ban_userid, :bigint
    end

    drop constraint(:phpbb_vote_voters, "phpbb_vote_voters_vote_user_id_fkey")

    alter table(:phpbb_vote_voters) do
      modify :vote_user_id, :bigint
    end

    drop constraint(:phpbb_privmsgs, "phpbb_privmsgs_privmsgs_from_userid_fkey")

    drop constraint(:phpbb_privmsgs, "phpbb_privmsgs_privmsgs_to_userid_fkey")

    alter table(:phpbb_privmsgs) do
      modify :privmsgs_to_userid, :bigint
      modify :privmsgs_from_userid, :bigint
    end

    drop constraint(:phpbb_sessions_keys, "phpbb_sessions_keys_user_id_fkey")

    alter table(:phpbb_sessions_keys) do
      modify :user_id, :bigint
    end

    drop constraint(:phpbb_user_group, "phpbb_user_group_user_id_fkey")

    alter table(:phpbb_user_group) do
      modify :user_id, :bigint
    end

    drop constraint(:phpbb_posts, "phpbb_posts_poster_id_fkey")

    alter table(:phpbb_posts) do
      modify :poster_id, :bigint
    end

    drop table(:phpbb_users)

    alter table(:users) do
      remove :username
      remove :phpbb_user_id
    end

    alter table(:phpbb_groups) do
      remove :group_description
      remove :group_type
      remove :group_single_user
      remove :group_moderator
      remove :group_name
    end

    drop constraint(:phpbb_auth_access, "phpbb_auth_access_group_id_fkey")

    drop constraint(:phpbb_auth_access, "phpbb_auth_access_forum_id_fkey")

    alter table(:phpbb_auth_access) do
      modify :forum_id, :bigint
      modify :group_id, :bigint
    end

    drop table(:phpbb_groups)

    drop constraint(:phpbb_confirm, "phpbb_confirm_session_id_fkey")

    drop table(:phpbb_confirm)

    drop constraint(:phpbb_vote_desc, "phpbb_vote_desc_topic_id_fkey")

    drop_if_exists unique_index(:phpbb_vote_desc, [:topic_id],
                     name: "phpbb_vote_desc_topic_id_phpbb_vote_desc_index_index"
                   )

    alter table(:phpbb_vote_desc) do
      remove :vote_length
      remove :vote_start
      remove :vote_text
      remove :topic_id
    end

    drop constraint(:phpbb_vote_voters, "phpbb_vote_voters_vote_id_fkey")

    alter table(:phpbb_vote_voters) do
      modify :vote_id, :bigint
    end

    drop table(:phpbb_vote_desc)

    alter table(:phpbb_sessions) do
      remove :session_admin
      remove :session_logged_in
      remove :session_page
      remove :session_ip
      remove :session_time
      remove :session_start
      remove :session_user_id
    end

    drop constraint(:phpbb_search_results, "phpbb_search_results_session_id_fkey")

    alter table(:phpbb_search_results) do
      modify :session_id, :bigint
    end

    drop table(:phpbb_sessions)

    drop constraint(:phpbb_topic_watch, "phpbb_topic_watch_topic_id_fkey")

    drop_if_exists unique_index(:phpbb_topic_watch, [:user_id],
                     name: "phpbb_topic_watch_user_id_phpbb_topics_watch_index_index"
                   )

    drop_if_exists unique_index(:phpbb_topic_watch, [:topic_id],
                     name: "phpbb_topic_watch_topic_id_phpbb_topics_watch_index_index"
                   )

    drop table(:phpbb_topic_watch)

    drop table(:phpbb_faq_items)

    drop table(:phpbb_ranks)

    drop constraint(:phpbb_topics, "phpbb_topics_forum_id_fkey")

    alter table(:phpbb_topics) do
      remove :topic_type
      remove :topic_vote
      remove :topic_status
      remove :topic_replies
      remove :topic_views
      remove :topic_time
      remove :topic_title
      remove :topic_moved_id
      remove :last_post_id
      remove :first_post_id
      remove :topic_poster
      remove :forum_id
    end

    drop constraint(:phpbb_posts, "phpbb_posts_topic_id_fkey")

    drop constraint(:phpbb_posts, "phpbb_posts_forum_id_fkey")

    alter table(:phpbb_posts) do
      modify :forum_id, :bigint
      modify :topic_id, :bigint
    end

    drop table(:phpbb_topics)

    drop_if_exists unique_index(:phpbb_search_wordmatch, [:word_id],
                     name: "phpbb_search_wordmatch_word_id_phpbb_search_wordmatch_index_index"
                   )

    drop_if_exists unique_index(:phpbb_search_wordmatch, [:post_id],
                     name: "phpbb_search_wordmatch_post_id_phpbb_search_wordmatch_index_index"
                   )

    drop table(:phpbb_search_wordmatch)

    drop table(:phpbb_pages)

    drop constraint(:phpbb_forum_prune, "phpbb_forum_prune_forum_id_fkey")

    drop table(:phpbb_forum_prune)

    drop constraint(:phpbb_posts_text, "phpbb_posts_text_post_id_fkey")

    drop table(:phpbb_posts_text)

    drop table(:phpbb_config)

    drop table(:phpbb_smilies)

    drop table(:phpbb_banlist)

    drop table(:phpbb_words)

    drop table(:phpbb_auth_access)

    drop table(:phpbb_disallow)

    drop_if_exists unique_index(:phpbb_search_results, [:session_id],
                     name: "phpbb_search_results_session_id_phpbb_search_results_index_index"
                   )

    drop table(:phpbb_search_results)

    drop_if_exists unique_index(:phpbb_vote_voters, [:vote_user_ip],
                     name: "phpbb_vote_voters_vote_user_ip_phpbb_vote_voters_index_index"
                   )

    drop_if_exists unique_index(:phpbb_vote_voters, [:vote_user_id],
                     name: "phpbb_vote_voters_vote_user_id_phpbb_vote_voters_index_index"
                   )

    drop_if_exists unique_index(:phpbb_vote_voters, [:vote_id],
                     name: "phpbb_vote_voters_vote_id_phpbb_vote_voters_index_index"
                   )

    drop table(:phpbb_vote_voters)

    drop constraint(:phpbb_privmsgs_text, "phpbb_privmsgs_text_privmsgs_text_id_fkey")

    drop table(:phpbb_privmsgs_text)

    drop_if_exists unique_index(:phpbb_privmsgs, [:privmsgs_to_userid],
                     name: "phpbb_privmsgs_privmsgs_to_userid_phpbb_privmsgs_index_index"
                   )

    drop_if_exists unique_index(:phpbb_privmsgs, [:privmsgs_from_userid],
                     name: "phpbb_privmsgs_privmsgs_from_userid_phpbb_privmsgs_index_index"
                   )

    drop table(:phpbb_privmsgs)

    drop constraint(:phpbb_forums, "phpbb_forums_forum_last_post_id_fkey")

    drop constraint(:phpbb_forums, "phpbb_forums_cat_id_fkey")

    drop_if_exists unique_index(:phpbb_forums, [:forum_id],
                     name: "phpbb_forums_forum_id_phpbb_forums_index_index"
                   )

    drop table(:phpbb_forums)

    alter table(:phpbb_themes) do
      remove :img_size_privmsg
      remove :img_size_poll
      remove :span_class3
      remove :span_class2
      remove :span_class1
      remove :fontcolor3
      remove :fontcolor2
      remove :fontcolor1
      remove :fontsize3
      remove :fontsize2
      remove :fontsize1
      remove :fontface3
      remove :fontface2
      remove :fontface1
      remove :td_color3
      remove :td_color2
      remove :td_color1
      remove :tr_class3
      remove :tr_class2
      remove :tr_class1
      remove :tr_color3
      remove :tr_color2
      remove :tr_color1
      remove :body_hlink
      remove :body_alink
      remove :body_vlink
      remove :body_link
      remove :body_text
      remove :body_bgcolor
      remove :head_stylesheet
      remove :template_name
      remove :style_name
    end

    drop constraint(:phpbb_themes_name, "phpbb_themes_name_themes_id_fkey")

    alter table(:phpbb_themes_name) do
      modify :themes_id, :bigint
    end

    drop table(:phpbb_themes)

    drop table(:phpbb_categories)

    drop table(:phpbb_sessions_keys)

    drop_if_exists unique_index(:phpbb_user_group, [:user_id],
                     name: "phpbb_user_group_user_id_phpbb_user_group_index_index"
                   )

    drop_if_exists unique_index(:phpbb_user_group, [:group_id],
                     name: "phpbb_user_group_group_id_phpbb_user_group_index_index"
                   )

    drop table(:phpbb_user_group)

    drop table(:phpbb_themes_name)

    drop table(:phpbb_posts)
  end
end
