defmodule Samba.Repo.Migrations.AddCountry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:facts, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :fact, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:users) do
      add :country, :text, default: "xx"
    end
  end

  def down do
    alter table(:users) do
      remove :country
    end

    drop table(:facts)
  end
end
