defmodule Samba.Repo.Migrations.AddPhpPostsRelations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:phpbb_posts) do
      modify :topic_id,
             references(:phpbb_topics,
               column: :topic_id,
               name: "phpbb_posts_topic_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :forum_id,
             references(:phpbb_forums,
               column: :forum_id,
               name: "phpbb_posts_forum_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :poster_id,
             references(:phpbb_users,
               column: :user_id,
               name: "phpbb_posts_poster_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create index(:phpbb_posts, [:topic_id])

    create index(:phpbb_posts, [:forum_id])

    create index(:phpbb_posts, [:poster_id])
  end

  def down do
    drop_if_exists index(:phpbb_posts, [:poster_id])

    drop_if_exists index(:phpbb_posts, [:forum_id])

    drop_if_exists index(:phpbb_posts, [:topic_id])

    drop constraint(:phpbb_posts, "phpbb_posts_topic_id_fkey")

    drop constraint(:phpbb_posts, "phpbb_posts_forum_id_fkey")

    drop constraint(:phpbb_posts, "phpbb_posts_poster_id_fkey")

    alter table(:phpbb_posts) do
      modify :poster_id, :bigint
      modify :forum_id, :bigint
      modify :topic_id, :bigint
    end
  end
end
