defmodule Samba.Repo.Migrations.PhpbbBools do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:phpbb_forums) do
      modify :auth_attachments, :boolean, default: false
      modify :auth_vote, :boolean, default: false
      modify :auth_pollcreate, :boolean, default: false
      modify :auth_sticky, :boolean, default: false
      modify :auth_announce, :boolean, default: false
      modify :auth_delete, :boolean, default: false
      modify :auth_edit, :boolean, default: false
      modify :auth_reply, :boolean, default: false
      modify :auth_post, :boolean, default: false
      modify :auth_read, :boolean, default: true
      modify :auth_view, :boolean, default: true
      modify :prune_next, :boolean, null: false, default: false
      modify :prune_enable, :boolean, default: false
      modify :forum_status, :boolean, default: false
    end

    alter table(:phpbb_privmsgs) do
      modify :privmsgs_attach_sig, :boolean, default: true
      modify :privmsgs_enable_smilies, :boolean, default: true
      modify :privmsgs_enable_html, :boolean, default: true
      modify :privmsgs_enable_bbcode, :boolean, default: true
    end

    alter table(:phpbb_auth_access) do
      modify :auth_mod, :boolean, default: false
      modify :auth_attachments, :boolean, default: false
      modify :auth_pollcreate, :boolean, default: false
      modify :auth_vote, :boolean, default: false
      modify :auth_announce, :boolean, default: false
      modify :auth_sticky, :boolean, default: false
      modify :auth_delete, :boolean, default: false
      modify :auth_edit, :boolean, default: false
      modify :auth_reply, :boolean, default: false
      modify :auth_post, :boolean, default: false
      modify :auth_read, :boolean, default: false
    end

    alter table(:phpbb_topics) do
      modify :topic_vote, :boolean, default: false
      modify :topic_status, :boolean, default: true
    end

    alter table(:phpbb_ranks) do
      modify :rank_special, :boolean, default: false
    end

    alter table(:phpbb_users) do
      modify :user_session_page, :boolean, default: true
      modify :user_active, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:phpbb_users) do
      modify :user_active, :bigint, null: true, default: nil
      modify :user_session_page, :bigint, default: 0
    end

    alter table(:phpbb_ranks) do
      modify :rank_special, :bigint, default: 0
    end

    alter table(:phpbb_topics) do
      modify :topic_status, :bigint, default: 0
      modify :topic_vote, :bigint, default: 0
    end

    alter table(:phpbb_auth_access) do
      modify :auth_read, :bigint, default: 0
      modify :auth_post, :bigint, default: 0
      modify :auth_reply, :bigint, default: 0
      modify :auth_edit, :bigint, default: 0
      modify :auth_delete, :bigint, default: 0
      modify :auth_sticky, :bigint, default: 0
      modify :auth_announce, :bigint, default: 0
      modify :auth_vote, :bigint, default: 0
      modify :auth_pollcreate, :bigint, default: 0
      modify :auth_attachments, :bigint, default: 0
      modify :auth_mod, :bigint, default: 0
    end

    alter table(:phpbb_privmsgs) do
      modify :privmsgs_enable_bbcode, :bigint, default: 1
      modify :privmsgs_enable_html, :bigint, default: 0
      modify :privmsgs_enable_smilies, :bigint, default: 1
      modify :privmsgs_attach_sig, :bigint, default: 1
    end

    alter table(:phpbb_forums) do
      modify :forum_status, :bigint, default: 0
      modify :prune_enable, :bigint, default: 0
      modify :prune_next, :bigint, null: true, default: nil
      modify :auth_view, :bigint, default: 0
      modify :auth_read, :bigint, default: 0
      modify :auth_post, :bigint, default: 0
      modify :auth_reply, :bigint, default: 0
      modify :auth_edit, :bigint, default: 0
      modify :auth_delete, :bigint, default: 0
      modify :auth_announce, :bigint, default: 0
      modify :auth_sticky, :bigint, default: 0
      modify :auth_pollcreate, :bigint, default: 0
      modify :auth_vote, :bigint, default: 0
      modify :auth_attachments, :bigint, default: 0
    end
  end
end
