defmodule Samba.Repo.Migrations.Modify do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:phpbb_posts_text) do
      add :clean_bbcode, :text
      add :ast, :map
    end
  end

  def down do
    alter table(:phpbb_posts_text) do
      remove :ast
      remove :clean_bbcode
    end
  end
end
